// This file is generated by forge doc. Do not edit manually.
// Re-run `forge doc` to update.

export const sidebar = [
    {
      text: "src",
      items: [
        {
          text: "Contracts",
          collapsed: true,
          items: [
            { text: "AccessManager", link: "/src/contract.AccessManager" },
            { text: "EIP712Swap", link: "/src/contract.EIP712Swap" },
            { text: "FeeManager", link: "/src/contract.FeeManager" },
            { text: "LiquidityPool", link: "/src/contract.LiquidityPool" },
            { text: "VaultMultisig", link: "/src/contract.VaultMultisig" },
          ],
        },
        {
          text: "Interfaces",
          collapsed: true,
          items: [
            { text: "ISwap", link: "/src/interface.ISwap" },
          ],
        },
        {
          text: "Libraries",
          collapsed: true,
          items: [
            { text: "Roles", link: "/src/library.Roles" },
          ],
        },
      ],
    },
]
